pipeline{
    agent {
        label 'slave3'
    }
    
    stages{
        stage('build1'){
            steps{
                sh '''
                    echo "Calling Build stage"
                '''
            }
        }
        
        stage('test1'){
            steps{
                sh '''
                    echo "Verification stage completed."
                '''
            }
        }
        
        stage('deploy1'){
            steps{
                sh '''
                    bash ${WORKSPACE}/script.sh
                    echo "Deployment successful"
                '''
            }
        }
    }
}
