pipeline{
  agent any

 stages{
     stage('build'){
           steps{
                sh '''
                      echo "Build is completed"
                   '''
         }
    }
   stage ('deploy'){
     steps{
        sh '''
               echo "deployment is successful"
               '''
   
}
}
